// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzR2coAz-tuerMHG0KRzR97Jf3cKzh4s',
    appId: '1:599037125617:web:c01d7d02f5ff3db25c5a50',
    messagingSenderId: '599037125617',
    projectId: 'easy-shopper-69df9',
    authDomain: 'easy-shopper-69df9.firebaseapp.com',
    storageBucket: 'easy-shopper-69df9.appspot.com',
    measurementId: 'G-DTTKWH4N6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbn6eAQDXDihBg5SnldNLNzKl84Flv2k',
    appId: '1:599037125617:android:f6b7413090b6fbda5c5a50',
    messagingSenderId: '599037125617',
    projectId: 'easy-shopper-69df9',
    storageBucket: 'easy-shopper-69df9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMjs0fxyNX_WHl_Am6xhcn74gkYIh4RwE',
    appId: '1:599037125617:ios:3f81f736f3a787945c5a50',
    messagingSenderId: '599037125617',
    projectId: 'easy-shopper-69df9',
    storageBucket: 'easy-shopper-69df9.appspot.com',
    iosClientId: '599037125617-gchltlcutmk0dud3b49hln4m7i5a3b9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduation.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMjs0fxyNX_WHl_Am6xhcn74gkYIh4RwE',
    appId: '1:599037125617:ios:3f81f736f3a787945c5a50',
    messagingSenderId: '599037125617',
    projectId: 'easy-shopper-69df9',
    storageBucket: 'easy-shopper-69df9.appspot.com',
    iosClientId: '599037125617-gchltlcutmk0dud3b49hln4m7i5a3b9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduation.graduationProject',
  );
}
